#!/opt/homebrew/bin/fish

#            _         _     
#        ___| |_   ___| |__  
#       / __| __| / __| '_ \ 
#      | (__| |_ _\__ \ | | |
#       \___|\__(_)___/_| |_|
#    
# ct.sh - cd and create a tmux session

set path $argv[1]
set name (basename "$path")

# if tmux is not running
if not pgrep tmux
    tmux new-session -s $name -c $path
    exit 0
end

if tmux has-session -t $name
    echo has session
else
    echo creating new session
    tmux new-session -s $name -c $path -d 
end

# if tmux is attached
if set -q TMUX
    echo switching client
    tmux switch-client -t $name
else 
    echo attaching
    tmux attach -t $name
end

# vim: ft=fish
